Add base interfaces for future implementation
kysect/EditorConfigEditor pull request #1
Opened 2023-07-21 17:39 UTC by FrediKats

Закинул ридми, которую писали. Закинул базовые интерфейсы и модели, чтобы заапрувить предварительный дизайн и можно было задачи независимо расписать на реализацию.

2023-07-22 07:05 UTC, FrediKats commented
Сделал драфтом. Появились некоторые мысли на тему нейминга, планирую немного изменить.

2023-07-22 09:17 UTC, annchous commented on Readme.md
> +  - Реализовать парсер editorconfig
Повторяется задача"Реализовать парсер editorconfig"

2023-07-22 09:21 UTC, annchous commented on Sources/EditorConfigEditor.Core/MicrosoftLearnDocumentation/IMicrosoftLearnDocumentationInfoProvider.cs
> +public interface IMicrosoftLearnDocumentationInfoProvider
Может быть сократить до IMsLearn<...>?

2023-07-22 09:38 UTC, FrediKats commented on Readme.md
> +  - Реализовать парсер editorconfig
Угу. Это подзадача, которую нужно реализовать два двух разных сценариев. Решил оставить, чтобы сценарии читались полноценно.

2023-07-22 09:39 UTC, FrediKats commented on Sources/EditorConfigEditor.Core/MicrosoftLearnDocumentation/IMicrosoftLearnDocumentationInfoProvider.cs
> +public interface IMicrosoftLearnDocumentationInfoProvider
Можно в Глоссарий написать, что у нас будет сокращение Msl, которое будет означать Microsoft Learn!

2023-07-22 09:46 UTC, Bibletoon requested changes
Request changes потому из-за смешения RoslynRules и EditorConfig

2023-07-22 09:46 UTC, Bibletoon commented on Sources/EditorConfigEditor.Core/EditorConfigParsing/EditorConfigRuleSet.cs
> +    public IReadOnlyCollection<IEditorConfigRule> Rows { get; }
Название `Rows` мне как-то не нравится, идейно не очень подходит, но альтернативу предложить не могу

2023-07-22 09:46 UTC, Bibletoon commented on Sources/EditorConfigEditor.Core/MicrosoftLearnDocumentation/Models/MicrosoftLearnDocumentationRawInfo.cs
> +    public IReadOnlyCollection<string> StyleRuleInfo { get; }
Как будто бы множественного числа не хватает

2023-07-22 09:46 UTC, Bibletoon commented on Sources/EditorConfigEditor.Core/EditorConfigParsing/EditorConfigRuleSet.cs
> +    public IReadOnlyCollection<IEditorConfigRule> Rows { get; }
Плюс я правильно понимаю, что мы секции в эдитор конфиге пока не сапортим

2023-07-22 09:46 UTC, Bibletoon commented on Sources/EditorConfigEditor.Core/EditorConfigModels/RoslynStyleRule.cs
> +    public IReadOnlyCollection<EditorConfigStyleRuleOption> Options { get; }
Какое-то смешение зон `EditorConfig` и `Roslyn` произошло, чтобы по классу `EditorConfigStyleRuleOption` понять что он относится к `RoslynRule` пришлось воспользоваться поиском

2023-07-22 09:46 UTC, Bibletoon commented on Sources/EditorConfigEditor.Core/EditorConfigModels/EditorConfigStyleRuleOption.cs
> +    public IReadOnlyCollection<EditorConfigStyleRuleOptionValue> Options { get; }
Правильно ли я понимаючто вот такая опция `dotnet_naming_style.camel_case_style.capitalization` имеет три уровня, разделённые точкой, и `dotnet_naming_style` - это `RoslynStyleRule`, `camel_case` - это `EditorConfigStyleRuleOption`, а `capitalization` - это `EditorConfigStyleRuleOptionValue`

2023-07-22 09:46 UTC, Bibletoon commented on Sources/EditorConfigEditor.Core/EditorConfigModels/EditorConfigStyleRuleOption.cs
> +    public IReadOnlyCollection<EditorConfigStyleRuleOptionValue> Options { get; }
Ну и если так, то гарантируется ли спецификацией то, что этих уровней всегда три?

2023-07-22 15:14 UTC, s4xack commented on Sources/EditorConfigEditor.Core/EditorConfigParsing/EditorConfigRuleSet.cs
> +    public IReadOnlyCollection<IEditorConfigRule> Rows { get; }
А в чем проблема коллекцию правил назвать `Rules`?

2023-07-22 15:22 UTC, FrediKats commented on Sources/EditorConfigEditor.Core/EditorConfigParsing/EditorConfigRuleSet.cs
> +    public IReadOnlyCollection<IEditorConfigRule> Rows { get; }
Да, пока не саппортим.

2023-07-22 15:29 UTC, FrediKats commented on Sources/EditorConfigEditor.Core/EditorConfigModels/RoslynStyleRule.cs
> +    public IReadOnlyCollection<EditorConfigStyleRuleOption> Options { get; }
Да, криво переименовал, когда первые правки вносил.

2023-07-22 15:39 UTC, FrediKats commented on Sources/EditorConfigEditor.Core/EditorConfigModels/EditorConfigStyleRuleOption.cs
> +    public IReadOnlyCollection<EditorConfigStyleRuleOptionValue> Options { get; }
Нет, не так. На примере https://github.com/dotnet/docs/blob/main/docs/fundamentals/code-analysis/style-rules/ide0031.md.

- RoslynStyleRule - это Use null propagation (IDE0031)
- EditorConfigStyleRuleOption.Name - это dotnet_style_null_propagation
-  EditorConfigStyleRuleOptionValue.Value - это true (Prefer to use null-conditional operator when possible)
-  EditorConfigStyleRuleOptionValue.Description - это Prefer to use null-conditional operator when possible

dotnet_naming_style.camel_case_style.capitalization нужно будет как-то придумать во что парсить. Скорее всего:
- EditorConfigStyleRuleOption.Name - dotnet_naming_style.camel_case_style.capitalization
- EditorConfigStyleRuleOptionValue.Value - это camel_case
, это всё будет EditorConfigStyleRuleOption, где "" - это Name, а значение - это то, что может быть в значениях

2023-07-22 15:39 UTC, FrediKats commented on Sources/EditorConfigEditor.Core/MicrosoftLearnDocumentation/Models/MicrosoftLearnDocumentationRawInfo.cs
> +    public IReadOnlyCollection<string> StyleRuleInfo { get; }
Fixed

2023-07-22 17:28 UTC, Bibletoon commented on Sources/EditorConfigEditor.Core/RoslynRuleModels/RoslynStyleRuleOption.cs
> +    public IReadOnlyCollection<EditorConfigStyleRuleOptionValue> Options { get; }
Тут тоже забыл заренеймить?

2023-07-23 09:02 UTC, FrediKats commented on Sources/EditorConfigEditor.Core/EditorConfigModels/EditorConfigStyleRuleOption.cs
> +    public IReadOnlyCollection<EditorConfigStyleRuleOptionValue> Options { get; }
Я ишуе на реализацию парсера опишем это всё.

2023-07-23 09:03 UTC, merged